CREATE DATABASE LibraryManage;
USE LibraryManage;

CREATE TABLE Books(
    bookId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Author VARCHAR(100) NOT NULL,
    isAvailable BOOLEAN NOT NULL 
)

CREATE TABLE Users(
    UserId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(100) NOT NULL,
    phoneNumber VARCHAR(20) NOT NULL
)